"""Example 19: Multi-table Management with Forensic Audit & SQLite Backup in WPostgreSQL.

This example demonstrates:
1. Multi-table initialization with Pydantic BaseModel inheritance.
2. Automatic ID Primary Key handling (omitted in model definitions, auto-generated by WPostgreSQL).
3. Intuitive Foreign Key relationship definitions using ForeignType (ONE_ONE, ONE_MANY, MANY_MANY):
   - foreign_key=TargetModel (passes model class directly)
   - foreign_type=ForeignType.ONE_ONE, ONE_MANY, MANY_MANY
4. Forensic audit trail (forensic=True) applied automatically across all models.
5. Type-safe CRUD operations with user tracking (user_id).
6. Querying records via repository API without using raw SQL or get_connection.
7. Exporting multi-table database backup to an SQLite file using backup_db_to_sqlite.
"""

from pathlib import Path
from typing import List, Dict, Any
from pydantic import BaseModel, Field
from wpostgresql import WPostgreSQL, ForeignType, backup_db_to_sqlite

# Database connection configuration
db_config: Dict[str, Any] = {
    "dbname": "wpostgresql",
    "user": "postgres",
    "password": "postgres",
    "host": "localhost",
    "port": 5432,
}


# -----------------------------------------------------------------------------
# 1. Domain Models demonstrating ForeignType (ONE_ONE, ONE_MANY, MANY_MANY)
# -----------------------------------------------------------------------------
class Customer(BaseModel):
    """Customer entity model (Primary Entity)."""

    name: str = Field(description="Customer full name")
    email: str = Field(description="Customer email address")


class CustomerProfile(BaseModel):
    """Customer profile entity model with 1:1 relationship to Customer."""

    customer_id: int = Field(
        description="Interconexion a la tabla Customer",
        json_schema_extra={
            "foreign_key": Customer,
            "foreign_type": ForeignType.ONE_ONE,
        },
    )
    tax_id: str = Field(description="Tax identification number")
    phone: str = Field(description="Contact phone number")


class Invoice(BaseModel):
    """Invoice header model with 1:N relationship to Customer."""

    customer_id: int = Field(
        description="Interconexion a la tabla Customer",
        json_schema_extra={
            "foreign_key": Customer,
            "foreign_type": ForeignType.ONE_MANY,
        },
    )
    total_amount: float
    description: str


class Tag(BaseModel):
    """Tag model for N:M labeling."""

    name: str = Field(description="Tag label name", json_schema_extra={"unique": True})


class InvoiceTag(BaseModel):
    """Junction table for N:M relationship between Invoice and Tag."""

    invoice_id: int = Field(
        description="Interconexion a la tabla Invoice",
        json_schema_extra={
            "foreign_key": Invoice,
            "foreign_type": ForeignType.MANY_MANY,
        },
    )
    tag_id: int = Field(
        description="Interconexion a la tabla Tag",
        json_schema_extra={
            "foreign_key": Tag,
            "foreign_type": ForeignType.MANY_MANY,
        },
    )


# -----------------------------------------------------------------------------
# 2. Database Initialization & Reset
# -----------------------------------------------------------------------------
def init_database() -> tuple[WPostgreSQL, List[type]]:
    """Initialize WPostgreSQL instance with multi-table models and forensic auditing."""
    print("--- Step 1: Initializing WPostgreSQL in Multi-Table Forensic Mode ---")
    models = [Customer, CustomerProfile, Invoice, Tag, InvoiceTag]

    # Clean existing tables for clean execution
    cleaner = WPostgreSQL(models, db_config)
    for m in reversed(models):
        try:
            cleaner[m]._sync.drop_table()
        except Exception:
            pass

    db = WPostgreSQL(models, db_config, forensic=True)
    return db, models


# -----------------------------------------------------------------------------
# 3. Data Insertion Function (ONE_ONE, ONE_MANY, MANY_MANY)
# -----------------------------------------------------------------------------
def insert_relational_data(db: WPostgreSQL) -> None:
    """Insert relational entities across ONE_ONE, ONE_MANY, and MANY_MANY relationships."""
    print("\n--- Step 2: Inserting Relational Data (ONE_ONE, ONE_MANY, MANY_MANY) ---")

    # A. Insert Customer (Auto ID = 1)
    cust = Customer(name="William Rodriguez", email="william@example.com")
    inserted_cust = db.insert(cust, user_id=101)
    cust_id = getattr(inserted_cust, "id", 1)

    # B. Insert 1:1 CustomerProfile (ONE_ONE)
    profile = CustomerProfile(customer_id=cust_id, tax_id="ES-12345678X", phone="+34 600000000")
    db.insert(profile, user_id=101)
    print(f"Inserted ONE_ONE CustomerProfile linked to Customer #{cust_id}")

    # C. Insert 1:N Invoices (ONE_MANY)
    inv1 = Invoice(customer_id=cust_id, total_amount=250.00, description="Software License")
    inv2 = Invoice(customer_id=cust_id, total_amount=99.99, description="Cloud Hosting")
    inserted_inv1 = db.insert(inv1, user_id=202)
    inserted_inv2 = db.insert(inv2, user_id=202)
    inv1_id = getattr(inserted_inv1, "id", 1)
    print(f"Inserted ONE_MANY Invoices linked to Customer #{cust_id}")

    # D. Insert Tags & N:M Links (MANY_MANY)
    t1 = Tag(name="VIP")
    t2 = Tag(name="Recurring")
    inserted_t1 = db.insert(t1, user_id=303)
    inserted_t2 = db.insert(t2, user_id=303)
    t1_id = getattr(inserted_t1, "id", 1)
    t2_id = getattr(inserted_t2, "id", 2)

    # Link Invoice #1 to Tag #1 (VIP) and Tag #2 (Recurring)
    db.insert(InvoiceTag(invoice_id=inv1_id, tag_id=t1_id), user_id=303)
    db.insert(InvoiceTag(invoice_id=inv1_id, tag_id=t2_id), user_id=303)
    print(f"Inserted MANY_MANY InvoiceTag links connecting Invoice #{inv1_id} with Tags 'VIP' & 'Recurring'")


# -----------------------------------------------------------------------------
# 4. Data Querying Function
# -----------------------------------------------------------------------------
def query_relational_data(db: WPostgreSQL) -> None:
    """Query and display active relational records using WPostgreSQL repository API."""
    print("\n--- Step 3: Querying Relational Data ---")

    # Fetch Customer #1
    customer = db[Customer].get(1)
    if customer:
        print(f"Customer: [{getattr(customer, 'id', 1)}] {customer.name} ({customer.email})")

    # Query ONE_ONE Profile
    profiles = db[CustomerProfile].filter(customer_id=1)
    if profiles:
        p = profiles[0]
        print(f"  ONE_ONE Profile -> Tax ID: {p.tax_id}, Phone: {p.phone}")

    # Query ONE_MANY Invoices
    invoices = db.invoice.filter(customer_id=1)
    print(f"  ONE_MANY Invoices ({len(invoices)}):")
    for inv in invoices:
        inv_id = getattr(inv, "id", 1)
        print(f"    - Invoice #{inv_id}: ${inv.total_amount:.2f} ({inv.description})")

        # Query MANY_MANY Tags for this invoice via InvoiceTag junction table
        junction_links = db[InvoiceTag].filter(invoice_id=inv_id)
        tag_ids = [link.tag_id for link in junction_links]
        tags = [db[Tag].get(tid) for tid in tag_ids if db[Tag].get(tid) is not None]
        tag_names = ", ".join([t.name for t in tags])
        print(f"      Tags (MANY_MANY): [{tag_names}]")


# -----------------------------------------------------------------------------
# 5. SQLite Backup Export Function
# -----------------------------------------------------------------------------
def export_sqlite_backup(models: List[type], sqlite_path: Path) -> None:
    """Export all multi-table database contents into an SQLite database file."""
    print(f"\n--- Step 4: Exporting Multi-Table SQLite Backup to '{sqlite_path}' ---")
    backup_results = backup_db_to_sqlite(models, db_config, sqlite_path)

    print("Backup completed successfully:")
    for table_name, count in backup_results.items():
        print(f"  - Table [{table_name}]: {count} records exported")


# -----------------------------------------------------------------------------
# Main Execution Workflow
# -----------------------------------------------------------------------------
def main() -> None:
    """Orchestrate the multi-table forensic audit and SQLite backup demonstration."""
    db, models = init_database()
    insert_relational_data(db)
    query_relational_data(db)

    sqlite_file = Path("multi_table_forensic_backup.db")
    export_sqlite_backup(models, sqlite_file)

    print("\nAll steps executed successfully!")


if __name__ == "__main__":
    main()
